baseURL = "https://burnett.wtf"
title   = "UnDeR mAj0r CoNsTrUcT1On"
languageCode = "en-us"


#theme = "hugo-theme-hello-friend-ng" # original theme
theme = "hugo-theme-hello-friend-ng_jlb-edits" # JLB edits

copyright = "CC0"

[author]
  name = "J. Burnett"
[permalinks]
  Posts = "/posts/:year/:month/:title/"

# Metadata mostly used in document's head
  description = ""
  keywords = "research, ecologist, data science, usgs, birds, ornithology, avian"
  images = [""]

# Home page subtitles
  homeSubtitle = "Research Ecologist & Mendenhall Postdoctoral Fellow"
 # homeSubtitle2 = "Science Analytics & Synthesis"
  homeSubtitle3 = "U.S. Geological Survey"

# Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

# Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

# Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

# Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/trashbirdecology"
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/trashbirdecol"
  [[params.social]]
    name = "email"
    url  = "mailto:jessicaleighburnett@gmail.com"
  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/4137899/jessica-burnett"

