baseURL = "https://burnett.wtf"
title   = "UnDeR mAj0r CoNsTrUcT1On"
languageCode = "en-us"


#theme = "hugo-theme-hello-friend-ng" # original theme
theme = "hugo-theme-hello-friend-ng_jlb-edits" # JLB edits
